version: "3"

services:
  fpm:
   image: registry.cn-shanghai.aliyuncs.com/seaon/php-fpm:v1
   container_name: fpm
   volumes:
     - /media/sf_seaon/aa:/data
     - ./php/zzz-docker.conf:/usr/local/etc/php-fpm.d/zzz-docker.conf
   command: ["php-fpm", "-R"]

  nginx:
   image: nginx:1.13.9-alpine
   container_name: nginx
   ports:
      - 8080:80
   volumes:
      - /media/sf_seaon/aa:/data
      - ~/logs:/logs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/conf.d
