version: "3"

services:
  fpm:
   image: php:7.2.0-fpm-alpine3.7
   container_name: fpm
   volumes:
      - /data:/data
   networks:
      - default

  nginx:
   image: nginx:1.13.9-alpine
   container_name: nginx
   ports:
      - 8080:80
   volumes:
      - /data:/data
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx:/etc/nginx/conf.d
   networks:
      - default

networks:
    default:
